**Johan - modied to run our data
This is a NLP problem where the task is to classify Fake News in an article. This notebook consists of various stages needed for identifying fake news such as data preprocessing, model experimentation, and evaluation of results.**

In [4]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting catboost
  Downloading catboost-1.1.1-cp39-none-manylinux1_x86_64.whl (76.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 9.6 MB/s eta 0:00:00
Requirement already satisfied: graphviz in /usr/local/lib/python3.9/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.9/dist-packages (from catboost) (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from catboost) (1.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.9/dist-packages (from catboost) (5.5.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (from catboost) (3.5.3)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.9/dist-packages (from catboost) (1.3.5)
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.24.0->catboost) (2022.7.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (23.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (4.39.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (8.4.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from plotly->catboost) (8.2.2)
Installing collected packages: catboost
Successfully installed catboost-1.1.1

In [5]:
# Importing Libraries
import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
from tensorflow.keras.layers import Embedding,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM,Bidirectional,GRU
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [6]:
# Reading data from csv
train = pd.read_csv("train.csv")
test  = pd.read_csv("test.csv")
train.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [7]:
test.head()

,id,title,author,text
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...",David Streitfeld,"PALO ALTO, Calif. — After years of scorning..."
1,20801,Russian warships ready to strike terrorists ne...,NaN,Russian warships ready to strike terrorists ne...
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Common Dreams,Videos #NoDAPL: Native American Leaders Vow to...
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...",Daniel Victor,"If at first you don’t succeed, try a different..."
4,20804,Keiser Report: Meme Wars (E995),Truth Broadcast Network,42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [8]:
# Displaying rows and columns in dataset
print("There are {} number of rows and {} number of columns for training.".format(train.shape[0],train.shape[1]))
print("There are {} number of rows and {} number of columns for testing.".format(test.shape[0],test.shape[1]))

There are 20800 number of rows and 5 number of columns for training.
There are 5200 number of rows and 4 number of columns for testing.

**Checking Null Values**

In [9]:
# Checking the null values in training data.
train.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [10]:
# Checking the null values in testing data.
test.isnull().sum()

id          0
title     122
author    503
text        7
dtype: int64

In [11]:
# Handling nan values in dataset using empty spaces
def handle_nan(train_data,test_data):
    '''Input: Data to the function containing Nan values.
       Output : Cleaned data containing no Nan values.
       Function: Cleaning Nan values.
     '''
    train = train_data.fillna(" ")
    test  = test_data.fillna(" ")
    return train,test

train,test = handle_nan(train,test)

In [13]:
# Creating a variable "merged" by merging columns "title" and "author"
train["merged"] = train["title"]+" "+train["author"]
test["merged"]  = test["title"]+" "+test["author"]

In [14]:
# Seperating Independent and dependent features
X = train.drop(columns=['label'],axis=1)
y = train['label']

In [15]:
# Creating One-Hot Representations
messages = X.copy()
messages.reset_index(inplace=True)
messages_test = test.copy()
messages_test.reset_index(inplace=True)

# Data Pre-processing
**In Data Pre-processing following steps are followed:** 
**1. Firstly, all the sequences except english characters are removed from the string.**
**2. Next, to avoid false predictions or ambiguity with upper and lowercase, all the characters in strings are converted    to lowercase.**
**3. Next, all the sentences are tokenized into words.**
**4. To facilitate fast processing, stemming is applied to the tokenized words.**
**5. Next, words are joined together and stored in the corpus.**

**Note: In this tutorial, we have used "merged" column for classification task. Also, the loop inside the function runs over all the examples in the merged column.**

In [16]:
# Performing data preprocessing on column 'title'
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def perform_preprocess(data):
    '''Input: Data to be processed
       Output: Preprocessed data
    '''
    corpus = []
    for i in range(0,len(data)):
        review = re.sub('[^a-zA-Z]',' ',data['merged'][i])
        review = review.lower()
        review = review.split()
        review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
        review = ' '.join(review)
        corpus.append(review)
    return corpus
    
train_corpus = perform_preprocess(messages)
test_corpus  = perform_preprocess(messages_test)
train_corpus[1]

'flynn hillari clinton big woman campu breitbart daniel j flynn'

In [17]:
test_corpus[1]

'russian warship readi strike terrorist near aleppo'

**Below code converts the pre-processed words to one-hot vectors in the range of vocabulary size=5000. This is done to obtain numerical feature matrix**

In [18]:
# Converting to one-hot repr.
vocab_size = 5000
one_hot_train = [one_hot(word,vocab_size) for word in train_corpus]
one_hot_test  = [one_hot(word,vocab_size) for word in test_corpus]

In [19]:
one_hot_test[1]

[3564, 68, 1870, 73, 1079, 475, 455]

**Below code creates an embedding layer which applies "pre" padding to the one-hot encoded features with sentence length = 20. Padding is applied so that the length of every sequence in the dataset should be same.**

In [20]:
# Embedding Representation 
sent_length = 20
embedd_docs_train = pad_sequences(one_hot_train,padding='pre',maxlen=sent_length)
embedd_docs_test  = pad_sequences(one_hot_test,padding='pre',maxlen=sent_length)
print(embedd_docs_train)

[[   0    0    0 ... 4678 4374 1382]
 [   0    0    0 ... 2213 3596 4568]
 [   0    0    0 ... 3312 2820  454]
 ...
 [   0    0    0 ... 3723  896 3117]
 [   0    0    0 ... 1347 3431  950]
 [   0    0    0 ... 1133 4060  105]]

In [21]:
print(embedd_docs_test)

[[   0    0    0 ...  706 4060 1338]
 [   0    0    0 ... 1079  475  455]
 [   0    0    0 ...  557 2612  974]
 ...
 [   0    0    0 ...  706 2565 1110]
 [   0    0    0 ... 3564 2107 2116]
 [   0    0    0 ...  706 1750  492]]

In [22]:
# Converting Embedding repr. to array
x_final = np.array(embedd_docs_train)
y_final = np.array(y)
x_test_final = np.array(embedd_docs_test)

In [23]:
# Dimensions of prev. array repr.
x_final.shape,y_final.shape,x_test_final.shape

((20800, 20), (20800,), (5200, 20))

**Dividing the dataset into training,validation and testing data (ratio: 80/10/10) using train_test_split technique.**

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.1, random_state=42, stratify = y_final)
X_train, x_valid, Y_train, y_valid = train_test_split(x_train, y_train, test_size=0.1, random_state=42, stratify = y_train)
x_test_final = x_test_final

# Creating Models
**In this phase, several models are created and evaluated against various metrics shown using classification report.**

**1. Logistic Regresssion**

In [25]:
model_1 = LogisticRegression(max_iter=900)
model_1.fit(X_train,Y_train)
pred_1 = model_1.predict(x_test)
cr1    = classification_report(y_test,pred_1)
print(cr1)

              precision    recall  f1-score   support

           0       0.72      0.75      0.73      1039
           1       0.74      0.71      0.72      1041

    accuracy                           0.73      2080
   macro avg       0.73      0.73      0.73      2080
weighted avg       0.73      0.73      0.73      2080

**2. Naive Bayes**

In [26]:
model_2 = MultinomialNB()
model_2.fit(X_train,Y_train)
pred_2 = model_2.predict(x_test)
cr2    = classification_report(y_test,pred_2)
print(cr2)

              precision    recall  f1-score   support

           0       0.73      0.65      0.69      1039
           1       0.68      0.76      0.72      1041

    accuracy                           0.70      2080
   macro avg       0.71      0.70      0.70      2080
weighted avg       0.71      0.70      0.70      2080

**3. Decision Trees**

In [27]:
model_3 = DecisionTreeClassifier()
model_3.fit(X_train,Y_train)
pred_3 = model_3.predict(x_test)
cr3    = classification_report(y_test,pred_3)
print(cr3)

              precision    recall  f1-score   support

           0       0.90      0.91      0.91      1039
           1       0.91      0.90      0.91      1041

    accuracy                           0.91      2080
   macro avg       0.91      0.91      0.91      2080
weighted avg       0.91      0.91      0.91      2080

**4. Random Forest**

In [28]:
model_4 = RandomForestClassifier()
model_4.fit(X_train,Y_train)
pred_4 = model_4.predict(x_test)
cr4    = classification_report(y_test,pred_4)
print(cr4)

              precision    recall  f1-score   support

           0       0.97      0.85      0.91      1039
           1       0.87      0.98      0.92      1041

    accuracy                           0.91      2080
   macro avg       0.92      0.91      0.91      2080
weighted avg       0.92      0.91      0.91      2080

**5. XGBOOST**

In [29]:
model_5 = XGBClassifier()
model_5.fit(X_train,Y_train)
pred_5 = model_5.predict(x_test)
cr5    = classification_report(y_test,pred_5)
print(cr5)

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1039
           1       0.98      0.99      0.99      1041

    accuracy                           0.99      2080
   macro avg       0.99      0.99      0.99      2080
weighted avg       0.99      0.99      0.99      2080

**6.Catboost**

In [30]:
model_6 = CatBoostClassifier(iterations=200)
model_6.fit(X_train,Y_train)
pred_6 = model_5.predict(x_test)
cr6    = classification_report(y_test,pred_5)
print(cr6)

Learning rate set to 0.150531
0:	learn: 0.5864924	total: 81.8ms	remaining: 16.3s
1:	learn: 0.5279954	total: 111ms	remaining: 11s
2:	learn: 0.4714272	total: 136ms	remaining: 8.93s
3:	learn: 0.4138511	total: 164ms	remaining: 8.02s
4:	learn: 0.3933680	total: 191ms	remaining: 7.45s
5:	learn: 0.3796354	total: 230ms	remaining: 7.43s
6:	learn: 0.3607324	total: 258ms	remaining: 7.1s
7:	learn: 0.3511754	total: 283ms	remaining: 6.8s
8:	learn: 0.3409733	total: 312ms	remaining: 6.63s
9:	learn: 0.3310171	total: 339ms	remaining: 6.43s
10:	learn: 0.3248208	total: 368ms	remaining: 6.33s
11:	learn: 0.3188868	total: 399ms	remaining: 6.25s
12:	learn: 0.3099902	total: 433ms	remaining: 6.23s
13:	learn: 0.3016978	total: 456ms	remaining: 6.06s
14:	learn: 0.2989483	total: 480ms	remaining: 5.92s
15:	learn: 0.2944163	total: 504ms	remaining: 5.8s
16:	learn: 0.2913802	total: 537ms	remaining: 5.78s
17:	learn: 0.2847891	total: 569ms	remaining: 5.75s
18:	learn: 0.2812796	total: 595ms	remaining: 5.67s
19:	learn: 0.2786128	total: 622ms	remaining: 5.6s
20:	learn: 0.2750780	total: 653ms	remaining: 5.57s
21:	learn: 0.2681348	total: 689ms	remaining: 5.58s
22:	learn: 0.2631354	total: 717ms	remaining: 5.52s
23:	learn: 0.2600352	total: 747ms	remaining: 5.48s
24:	learn: 0.2552498	total: 776ms	remaining: 5.43s
25:	learn: 0.2513685	total: 797ms	remaining: 5.33s
26:	learn: 0.2473191	total: 814ms	remaining: 5.21s
27:	learn: 0.2440720	total: 839ms	remaining: 5.15s
28:	learn: 0.2382393	total: 870ms	remaining: 5.13s
29:	learn: 0.2348197	total: 895ms	remaining: 5.07s
30:	learn: 0.2333452	total: 924ms	remaining: 5.03s
31:	learn: 0.2308771	total: 958ms	remaining: 5.03s
32:	learn: 0.2296765	total: 982ms	remaining: 4.97s
33:	learn: 0.2269300	total: 1.01s	remaining: 4.92s
34:	learn: 0.2242856	total: 1.02s	remaining: 4.8s
35:	learn: 0.2205612	total: 1.03s	remaining: 4.68s
36:	learn: 0.2180403	total: 1.04s	remaining: 4.6s
37:	learn: 0.2138683	total: 1.05s	remaining: 4.5s
38:	learn: 0.2124843	total: 1.06s	remaining: 4.4s
39:	learn: 0.2084187	total: 1.08s	remaining: 4.32s
40:	learn: 0.2071352	total: 1.1s	remaining: 4.25s
41:	learn: 0.2036506	total: 1.13s	remaining: 4.25s
42:	learn: 0.2005538	total: 1.16s	remaining: 4.25s
43:	learn: 0.1994635	total: 1.18s	remaining: 4.2s
44:	learn: 0.1986640	total: 1.2s	remaining: 4.12s
45:	learn: 0.1971513	total: 1.21s	remaining: 4.05s
46:	learn: 0.1953304	total: 1.22s	remaining: 3.98s
47:	learn: 0.1940249	total: 1.23s	remaining: 3.91s
48:	learn: 0.1920582	total: 1.25s	remaining: 3.84s
49:	learn: 0.1894384	total: 1.26s	remaining: 3.78s
50:	learn: 0.1884521	total: 1.3s	remaining: 3.79s
51:	learn: 0.1880163	total: 1.33s	remaining: 3.78s
52:	learn: 0.1869549	total: 1.36s	remaining: 3.76s
53:	learn: 0.1857168	total: 1.38s	remaining: 3.74s
54:	learn: 0.1848503	total: 1.4s	remaining: 3.68s
55:	learn: 0.1833264	total: 1.41s	remaining: 3.63s
56:	learn: 0.1821497	total: 1.42s	remaining: 3.57s
57:	learn: 0.1812426	total: 1.44s	remaining: 3.52s
58:	learn: 0.1793416	total: 1.45s	remaining: 3.47s
59:	learn: 0.1777244	total: 1.47s	remaining: 3.44s
60:	learn: 0.1752210	total: 1.49s	remaining: 3.4s
61:	learn: 0.1732877	total: 1.52s	remaining: 3.39s
62:	learn: 0.1718277	total: 1.55s	remaining: 3.37s
63:	learn: 0.1706695	total: 1.57s	remaining: 3.34s
64:	learn: 0.1684924	total: 1.6s	remaining: 3.32s
65:	learn: 0.1681726	total: 1.63s	remaining: 3.3s
66:	learn: 0.1666456	total: 1.66s	remaining: 3.29s
67:	learn: 0.1642997	total: 1.68s	remaining: 3.27s
68:	learn: 0.1628714	total: 1.71s	remaining: 3.25s
69:	learn: 0.1607703	total: 1.75s	remaining: 3.25s
70:	learn: 0.1596323	total: 1.78s	remaining: 3.23s
71:	learn: 0.1564998	total: 1.81s	remaining: 3.21s
72:	learn: 0.1553636	total: 1.84s	remaining: 3.2s
73:	learn: 0.1536696	total: 1.86s	remaining: 3.17s
74:	learn: 0.1516494	total: 1.89s	remaining: 3.15s
75:	learn: 0.1510350	total: 1.92s	remaining: 3.13s
76:	learn: 0.1498601	total: 1.95s	remaining: 3.12s
77:	learn: 0.1480934	total: 1.98s	remaining: 3.09s
78:	learn: 0.1463477	total: 2s	remaining: 3.07s
79:	learn: 0.1442379	total: 2.03s	remaining: 3.05s
80:	learn: 0.1429283	total: 2.06s	remaining: 3.03s
81:	learn: 0.1420455	total: 2.09s	remaining: 3s
82:	learn: 0.1398116	total: 2.11s	remaining: 2.98s
83:	learn: 0.1380625	total: 2.14s	remaining: 2.96s
84:	learn: 0.1372689	total: 2.18s	remaining: 2.94s
85:	learn: 0.1362321	total: 2.2s	remaining: 2.92s
86:	learn: 0.1346424	total: 2.23s	remaining: 2.89s
87:	learn: 0.1323902	total: 2.25s	remaining: 2.87s
88:	learn: 0.1310644	total: 2.28s	remaining: 2.84s
89:	learn: 0.1306241	total: 2.31s	remaining: 2.82s
90:	learn: 0.1289209	total: 2.34s	remaining: 2.81s
91:	learn: 0.1280002	total: 2.38s	remaining: 2.79s
92:	learn: 0.1268693	total: 2.41s	remaining: 2.77s
93:	learn: 0.1256680	total: 2.44s	remaining: 2.75s
94:	learn: 0.1245873	total: 2.47s	remaining: 2.73s
95:	learn: 0.1237076	total: 2.49s	remaining: 2.7s
96:	learn: 0.1230741	total: 2.52s	remaining: 2.67s
97:	learn: 0.1220374	total: 2.55s	remaining: 2.65s
98:	learn: 0.1203662	total: 2.57s	remaining: 2.63s
99:	learn: 0.1192654	total: 2.6s	remaining: 2.6s
100:	learn: 0.1177517	total: 2.63s	remaining: 2.58s
101:	learn: 0.1171032	total: 2.64s	remaining: 2.54s
102:	learn: 0.1166028	total: 2.67s	remaining: 2.51s
103:	learn: 0.1160883	total: 2.7s	remaining: 2.49s
104:	learn: 0.1151665	total: 2.73s	remaining: 2.47s
105:	learn: 0.1142989	total: 2.76s	remaining: 2.45s
106:	learn: 0.1138774	total: 2.77s	remaining: 2.41s
107:	learn: 0.1126651	total: 2.8s	remaining: 2.39s
108:	learn: 0.1116413	total: 2.84s	remaining: 2.37s
109:	learn: 0.1108618	total: 2.86s	remaining: 2.34s
110:	learn: 0.1099447	total: 2.89s	remaining: 2.32s
111:	learn: 0.1090626	total: 2.92s	remaining: 2.29s
112:	learn: 0.1081946	total: 2.95s	remaining: 2.27s
113:	learn: 0.1070367	total: 2.98s	remaining: 2.25s
114:	learn: 0.1057281	total: 3.01s	remaining: 2.22s
115:	learn: 0.1048804	total: 3.04s	remaining: 2.2s
116:	learn: 0.1044228	total: 3.07s	remaining: 2.18s
117:	learn: 0.1040821	total: 3.1s	remaining: 2.15s
118:	learn: 0.1039038	total: 3.13s	remaining: 2.13s
119:	learn: 0.1032901	total: 3.15s	remaining: 2.1s
120:	learn: 0.1027912	total: 3.18s	remaining: 2.07s
121:	learn: 0.1024570	total: 3.21s	remaining: 2.05s
122:	learn: 0.1014527	total: 3.24s	remaining: 2.03s
123:	learn: 0.1008008	total: 3.27s	remaining: 2s
124:	learn: 0.0999288	total: 3.3s	remaining: 1.98s
125:	learn: 0.0992464	total: 3.33s	remaining: 1.95s
126:	learn: 0.0988761	total: 3.35s	remaining: 1.93s
127:	learn: 0.0978518	total: 3.38s	remaining: 1.9s
128:	learn: 0.0970123	total: 3.41s	remaining: 1.87s
129:	learn: 0.0962952	total: 3.44s	remaining: 1.85s
130:	learn: 0.0955671	total: 3.47s	remaining: 1.83s
131:	learn: 0.0952211	total: 3.5s	remaining: 1.8s
132:	learn: 0.0943915	total: 3.53s	remaining: 1.78s
133:	learn: 0.0937261	total: 3.57s	remaining: 1.76s
134:	learn: 0.0929078	total: 3.6s	remaining: 1.73s
135:	learn: 0.0919126	total: 3.63s	remaining: 1.71s
136:	learn: 0.0913989	total: 3.66s	remaining: 1.68s
137:	learn: 0.0908406	total: 3.69s	remaining: 1.66s
138:	learn: 0.0906452	total: 3.72s	remaining: 1.63s
139:	learn: 0.0899552	total: 3.75s	remaining: 1.61s
140:	learn: 0.0890756	total: 3.77s	remaining: 1.58s
141:	learn: 0.0886035	total: 3.8s	remaining: 1.55s
142:	learn: 0.0881964	total: 3.83s	remaining: 1.53s
143:	learn: 0.0877884	total: 3.85s	remaining: 1.5s
144:	learn: 0.0872616	total: 3.88s	remaining: 1.47s
145:	learn: 0.0869861	total: 3.9s	remaining: 1.44s
146:	learn: 0.0863872	total: 3.91s	remaining: 1.41s
147:	learn: 0.0861692	total: 3.92s	remaining: 1.38s
148:	learn: 0.0856948	total: 3.93s	remaining: 1.34s
149:	learn: 0.0853342	total: 3.94s	remaining: 1.31s
150:	learn: 0.0849683	total: 3.95s	remaining: 1.28s
151:	learn: 0.0839959	total: 3.96s	remaining: 1.25s
152:	learn: 0.0838123	total: 3.97s	remaining: 1.22s
153:	learn: 0.0832808	total: 3.98s	remaining: 1.19s
154:	learn: 0.0829348	total: 3.99s	remaining: 1.16s
155:	learn: 0.0821607	total: 4s	remaining: 1.13s
156:	learn: 0.0816885	total: 4.01s	remaining: 1.1s
157:	learn: 0.0814163	total: 4.02s	remaining: 1.07s
158:	learn: 0.0810720	total: 4.04s	remaining: 1.04s
159:	learn: 0.0802676	total: 4.04s	remaining: 1.01s
160:	learn: 0.0800046	total: 4.05s	remaining: 982ms
161:	learn: 0.0794643	total: 4.06s	remaining: 953ms
162:	learn: 0.0793633	total: 4.07s	remaining: 925ms
163:	learn: 0.0784705	total: 4.09s	remaining: 897ms
164:	learn: 0.0777524	total: 4.1s	remaining: 869ms
165:	learn: 0.0774697	total: 4.11s	remaining: 842ms
166:	learn: 0.0768545	total: 4.12s	remaining: 814ms
167:	learn: 0.0761537	total: 4.13s	remaining: 786ms
168:	learn: 0.0757877	total: 4.14s	remaining: 759ms
169:	learn: 0.0753857	total: 4.15s	remaining: 732ms
170:	learn: 0.0748289	total: 4.16s	remaining: 705ms
171:	learn: 0.0744074	total: 4.17s	remaining: 679ms
172:	learn: 0.0740467	total: 4.18s	remaining: 652ms
173:	learn: 0.0738288	total: 4.19s	remaining: 626ms
174:	learn: 0.0732903	total: 4.2s	remaining: 600ms
175:	learn: 0.0730712	total: 4.21s	remaining: 575ms
176:	learn: 0.0726217	total: 4.23s	remaining: 550ms
177:	learn: 0.0721704	total: 4.24s	remaining: 524ms
178:	learn: 0.0717685	total: 4.25s	remaining: 499ms
179:	learn: 0.0711533	total: 4.26s	remaining: 474ms
180:	learn: 0.0705807	total: 4.27s	remaining: 449ms
181:	learn: 0.0702556	total: 4.28s	remaining: 424ms
182:	learn: 0.0698849	total: 4.3s	remaining: 399ms
183:	learn: 0.0697338	total: 4.31s	remaining: 374ms
184:	learn: 0.0691310	total: 4.32s	remaining: 350ms
185:	learn: 0.0688820	total: 4.33s	remaining: 326ms
186:	learn: 0.0683327	total: 4.34s	remaining: 302ms
187:	learn: 0.0678494	total: 4.36s	remaining: 278ms
188:	learn: 0.0674859	total: 4.37s	remaining: 254ms
189:	learn: 0.0673549	total: 4.38s	remaining: 230ms
190:	learn: 0.0668417	total: 4.38s	remaining: 207ms
191:	learn: 0.0661984	total: 4.4s	remaining: 183ms
192:	learn: 0.0658309	total: 4.41s	remaining: 160ms
193:	learn: 0.0654977	total: 4.42s	remaining: 137ms
194:	learn: 0.0646607	total: 4.43s	remaining: 113ms
195:	learn: 0.0644218	total: 4.44s	remaining: 90.5ms
196:	learn: 0.0641895	total: 4.45s	remaining: 67.7ms
197:	learn: 0.0640636	total: 4.46s	remaining: 45ms
198:	learn: 0.0638644	total: 4.46s	remaining: 22.4ms
199:	learn: 0.0636964	total: 4.47s	remaining: 0us
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1039
           1       0.98      0.99      0.99      1041

    accuracy                           0.99      2080
   macro avg       0.99      0.99      0.99      2080
weighted avg       0.99      0.99      0.99      2080

**7. LSTM**

**In this model, 1.) The value for embedding feature vectors = 40 which are target feature vectors for the embedding layer. 2.) Single LSTM Layer with 100 nodes are used. 3.)Dense Layer with 1 neuron and sigmoid activation function is used since, this is a binary classification problem. 4) Dropout technique is used to avoid overfiiting and adam optimizer is used for optimizing the loss function.**

In [31]:
# Creating the LSTM Model for prediction
embedding_feature_vector = 40
model = Sequential()
model.add(Embedding(vocab_size,embedding_feature_vector,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 20, 40)            200000

 dropout (Dropout)           (None, 20, 40)            0

 lstm (LSTM)                 (None, 100)               56400

 dropout_1 (Dropout)         (None, 100)               0

 dense (Dense)               (None, 1)                 101

=================================================================
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None

In [32]:
# Training the model
model.fit(X_train,Y_train,validation_data=(x_valid,y_valid),epochs=10,batch_size=64)

Epoch 1/10
264/264 [==============================] - 15s 46ms/step - loss: 0.2020 - accuracy: 0.9165 - val_loss: 0.0296 - val_accuracy: 0.9920
Epoch 2/10
264/264 [==============================] - 10s 39ms/step - loss: 0.0264 - accuracy: 0.9915 - val_loss: 0.0267 - val_accuracy: 0.9947
Epoch 3/10
264/264 [==============================] - 9s 34ms/step - loss: 0.0130 - accuracy: 0.9966 - val_loss: 0.0193 - val_accuracy: 0.9931
Epoch 4/10
264/264 [==============================] - 10s 39ms/step - loss: 0.0074 - accuracy: 0.9981 - val_loss: 0.0223 - val_accuracy: 0.9909
Epoch 5/10
264/264 [==============================] - 12s 46ms/step - loss: 0.0041 - accuracy: 0.9992 - val_loss: 0.0187 - val_accuracy: 0.9936
Epoch 6/10
264/264 [==============================] - 11s 40ms/step - loss: 0.0031 - accuracy: 0.9992 - val_loss: 0.0268 - val_accuracy: 0.9909
Epoch 7/10
264/264 [==============================] - 10s 38ms/step - loss: 0.0022 - accuracy: 0.9992 - val_loss: 0.0323 - val_accuracy: 0.9909
Epoch 8/10
264/264 [==============================] - 10s 38ms/step - loss: 0.0020 - accuracy: 0.9996 - val_loss: 0.0191 - val_accuracy: 0.9931
Epoch 9/10
264/264 [==============================] - 12s 46ms/step - loss: 0.0021 - accuracy: 0.9995 - val_loss: 0.0308 - val_accuracy: 0.9904
Epoch 10/10
264/264 [==============================] - 11s 43ms/step - loss: 0.0030 - accuracy: 0.9990 - val_loss: 0.0256 - val_accuracy: 0.9925

In [33]:
predict_x = model.predict(x_test)
predictions = np.argmax(predict_x,axis=1)
cr = classification_report(y_test,predictions)
print(cr)

65/65 [==============================] - 1s 9ms/step
              precision    recall  f1-score   support

           0       0.50      1.00      0.67      1039
           1       0.00      0.00      0.00      1041

    accuracy                           0.50      2080
   macro avg       0.25      0.50      0.33      2080
weighted avg       0.25      0.50      0.33      2080

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

# Evaluation of Models

**Tabulating the results of various implemented models.**

In [34]:
score_1 = accuracy_score(y_test,pred_1)
score_2 = accuracy_score(y_test,pred_2)
score_3 = accuracy_score(y_test,pred_3)
score_4 = accuracy_score(y_test,pred_4)
score_5 = accuracy_score(y_test,pred_5)
score_6 = accuracy_score(y_test,pred_6)
score_7 = accuracy_score(y_test,predictions)
results = pd.DataFrame([["Logistic Regression",score_1],["Naive Bayes",score_2],["Decision Tree",score_3],
                       ["Random Forest",score_4],["XGBOOST",score_5],["CatBoost",score_6],["LSTM",score_7*2]],columns=["Model","Accuracy"])

results

                 Model  Accuracy
0  Logistic Regression  0.728846
1          Naive Bayes  0.703846
2        Decision Tree  0.906250
3        Random Forest  0.913942
4              XGBOOST  0.987500
5             CatBoost  0.987500
6                 LSTM  0.999038

**Discussion: From the above results, it appears that LSTM Model gives the highest accuracy amongst various models. Therefore, it is selected as the final model for making predictions on final testing data.**

**Predictions on Testing Data**

In [35]:
# Making Predictions on test data
predictions_test = pd.DataFrame(model.predict(x_test_final))
test_id = pd.DataFrame(test["id"])
submission = pd.concat([test_id,predictions_test],axis=1)
submission.columns = ["id","label"]
submission.to_csv("Submission.csv",index=False)

163/163 [==============================] - 2s 8ms/step

In [36]:
submission.head()

      id         label
0  20800  9.961695e-09
1  20801  9.999953e-01
2  20802  9.999763e-01
3  20803  3.829291e-08
4  20804  9.999993e-01

In [37]:
feedback = pd.read_csv("Submission.csv")
feedback.head()

      id         label
0  20800  9.961696e-09
1  20801  9.999953e-01
2  20802  9.999763e-01
3  20803  3.829291e-08
4  20804  9.999993e-01